### ISSUE TITLE
請問為什麼start:renderer要分開?

### ISSUE THREAD

**Issue by RazgrizHsu** [lightyen/electron-react-typescript#1]
在`yarn start:renderer`會額外做render，
但是目前dev-server如果將其做為web打開，
因為環境是web，所以會拋出與Electron的相關異常，
竟然不能做為web開啟，為什麼這一段要分開呢？
還請指點一二，謝謝

另外請教，為什麼要使用awesome-typescript-loader，
而不直接使用babel-loader？因為我看babel-loader在專案裡也是ready的情況

**Comment by lightyen** [comment]
用 awesome-typescript-loader 是因為它能直接使用 tsc 來編譯 typescript，而不是像 babel 只是把 type 的部份去掉，以繞過 babel-loader 在處理 ts 所[不支援的部份](https://github.com/babel/babel/issues/8741)。當然直接用 awesome-typescript-loader 也能開發應用，但是我蠻喜歡 [react-hot-loader](https://github.com/gaearon/react-hot-loader) 而這個工具而它又依賴於 babel-loader，所以就兩個攪和在一塊囉。

另外為什麼要分兩個指令我還不太明白您的意思，start:main 是處理開發模式的 main process，而 start:renderer 是處理開發模式的 renderer process 的。

如果要讓 renderer process 的部份能被一般瀏覽器開啟，需要把 electron 的相關 code 移除，還有 webpack.config.js 的 output.publicPath 改成 "/" 才行。(也就是和前端開發單頁應用相同)

**Comment by RazgrizHsu** [comment]
原來如此，長知識了，謝謝指教

之所以會問這個問題，是因為像 [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) 它們就是只用babel-loader處理
我的確沒有想到支援的部份 0.0

抱歉，因為對electron並不熟悉，所以才會問為什麼要分兩邊
( 因為現在如果要開electron來一邊寫一邊改UI，必需要開兩個terminal )

不過話說，歸功於你的分類很清楚，
其實只要將Ipc.ts以及TitleBar.tsx兩個檔案裡面
window的部份mock一下，或是將語法改為 `currentWindow?.close()` 之後
在renderer的部份其實就可以在web裡開啟來了 (當然我還沒有想到你說的其他問題)

謝謝你的分享

**Comment by RazgrizHsu** [comment]
哦，話說在兩個指令的部份，我單純是提問，
但我喜歡你這樣的方式，就是單純UI的部份可以分開來測試
我覺得這個開發方式蠻理想的，因為一般的electron框架，都是直接開Electron的部份
( 就是跟 start:main 同樣效果 )

抱歉啊，因為不知道要在哪提問題，所以就寫在issue這邊了
你可以把這個issue關閉了，感謝你

**Comment by lightyen** [comment]
我似乎找到可以完全使用 babel 來處理 typescript 的方法了，估計近期會把 awesome-typescript-loader 給移除。

**Comment by RazgrizHsu** [comment]
用babel的方法的確有，我只是不能確定所有的支援都是沒問題的，

例如我自已的typescript專案，
我也不是用babel，我是在執行時期用typescript轉，跟ts-node一樣的做法，
https://github.com/TypeStrong/ts-node/blob/master/src/index.ts

因為像你這邊還要考慮dev時期的hot-reload，所以我不曉得這樣做是不是好的 0.0

**Comment by lightyen** [comment]
我剛剛試完沒發現什麼問題，hot-reload 也有在運作，我決定先衝一波了。

**Comment by lightyen** [comment]
哈哈，好吧…我還是遇到了許多困難，想要分開管理設定檔，但 babel 似乎不甩 tsconfig.json，果然前端部份全部交給 babel 處理還是有那麼點不現實...
@babel/preset-typescript 已放棄。

不過我最後還是決定移除 awesome-typescript-loader，以前它還不錯但現在已經月久失修，改使用 ts-loader 生態會更好，所以此專案依然是使用 tsc 處理 typescript。(換過來之後感覺編譯的更快了)

現在的設定：
- main: ts -> (ts-loader) -> js
- renderer: tsx -> (ts-loader + babel-loader) -> js

**Comment by RazgrizHsu** [comment]
是啊，我就是覺得babel在ts這邊還是有一點點差異，
而且假設ts的版本一但要換，還要改babel的設定檔
( 例如我有一個專案從3.4 昇到 3.8.2，光是 `someobject?.callfunc()` 就死掉了 )

awesome-typescript-loader我主要也是看他好像沒在維護了
感覺長久以往應該會有一些問題，所以才會想說是不是不該用他
